# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 21:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('watched', models.BooleanField(default=False)),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ControlPanel.Directory')),
            ],
        ),
        migrations.AddField(
            model_name='directory',
            name='last_watched_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_watched_file', to='ControlPanel.File'),
        ),
    ]
