# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlPanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='path',
            field=models.CharField(default=b'', max_length=500),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(default=b'', max_length=100),
        ),
    ]
